AWSTemplateFormatVersion: 2010-09-09
Description: 'bnkc-fnb: variables (variables that are required by other child stacks)'
Parameters:
  Product:
    Description: Concatenation of the Service name and the Connector Name. e.g. bnkc-fnb
    Type: String
  Environment:
    Description: Name of the environment. This will be used in all resource prefixes to differentiate between environments
    Type: String
  Timestamp:
    Description: 'Datetime this stack was created, to ensure it is always refreshed'
    Default: '2020-03-29T01:18:02.000Z'
    Type: String
Resources:
  StackDatetimeResource:
    Type: 'AWS::CloudFormation::WaitConditionHandle'
    Metadata:
      Comment: >-
        Dummy resource to make this a valid template. Because we set the meta data, this template will be evaluated as changed on every run
      StackDatetime: !Ref Timestamp
Outputs:
  StackName:
    Value: !Ref 'AWS::StackName'
    Description: Stack name for this stack
  Product:
    Value: !Ref Product
    Description: Product name - used in prefixes for all resources within these stacks
    Export:
      Name: !Sub '${AWS::StackName}-Product'
  Environment:
    Value: !Ref Environment
    Description: Environment name - used in prefixes for all resources within these stacks
    Export:
      Name: !Sub '${AWS::StackName}-Environment'
  S3BucketCFN:
    Value: !Sub  >-
      https://s3.amazonaws.com/${Product}-${Environment}-${AWS::Region}
    Description: Prefix for the parent folder on S3 which contains cloud formation templates for these stacks
    Export:
      Name: !Sub '${AWS::StackName}-S3BucketCFN'
  S3BucketPackage:
    Value: !Sub >-
      ${Product}-${Environment}-${AWS::Region}
    Description: Name of the s3 bucket which contains build output packages
    Export:
      Name: !Sub '${AWS::StackName}-S3BucketPackage'
  ParamStorePrefix:
    Value: !Sub >-
      /${Product}-${Environment}/cfn-exports
    Description: Prefix for values to be stored in param-store
    Export:
      Name: !Sub '${AWS::StackName}-ParamStorePrefix'
  SecretsManagerPrefix:
    Value: !Sub >-
      ${Product}-${Environment}/cfn-exports
    Description: Prefix for values to be stored in secrets manager
    Export:
      Name: !Sub '${AWS::StackName}-SecretsManagerPrefix'
  ResourcePrefix:
    Value: !Sub  >-
      ${Product}-${Environment}-${AWS::Region}
    Description: 'Prefix for use in resources. Format: <service>-<connector>-<environment>-<region>'
    Export:
      Name: !Sub '${AWS::StackName}-ResourcePrefix'
